package com.sql.hibrenate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ConstantsTab generated by hbm2java
 */
@Entity
@Table(name = "teacher")
public class TeacherTab implements java.io.Serializable {

	private String id;
	private String name;
	private String age;

	public TeacherTab() {
	}

	@Column(name = "name", length = 10)
	public String getName() {
		return name;
	}

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name = "id", nullable = false)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "age", length = 10)
	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}
}
